name: Build and Upload hda.img

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          # Update package list and install required tools
          sudo apt-get update
          sudo apt-get install -y parted dosfstools

      - name: Run pack-hda.sh script
        run: |
          chmod +x pack-hda.sh
          sudo ./pack-hda.sh

      - name: Upload hda.img artifact
        uses: actions/upload-artifact@v4
        with:
          name: hda-img
          path: hda.img
